server:
  port: 12020

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:12000/eureka/
  instance:
    instance-id: service-mq:12020
    prefer-ip-address: true # 优先注册IP地址而不是hostname
  healthcheck:
    enabled: true # 启用健康检查,注意:需要引用spring boot actuator

spring:
  application:
    name: mq-service
  rabbitmq:
    host: localhost
    port: 5672
    virtualHost: /local
    username: local
    password: local123

security:
  oauth2:
    resource:
      id: mq-service
      user-info-uri: http://localhost:18080/ua/oauth/user
      prefer-token-info: false

feign:
  hystrix:
    enabled: true

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 5000
  MaxAutoRetries: 1
hystrix:
  command:
    default:
      fallback:
        enabled: true
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
