server:
  port: 10010

spring:
  application:
    name: mq-service
  rabbitmq:
    host: localhost
    port: 5672
    virtualHost: /local
    username: local
    password: local123

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6001/eureka/
